"""ldl

Revision ID: 6594f4b92f6b
Revises: 4e111c4f64f3
Create Date: 2023-04-16 18:08:39.930952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6594f4b92f6b'
down_revision = '4e111c4f64f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
